### ISSUE TITLE
Second Add Attachments button in meta box

### ISSUE THREAD

**Issue by mwarwick** [DHolloran/wp-better-attachments#69]
When attaching a lot of files to a post using the metabox, the button at the top of the list scrolls off the page, although new attachments are loaded at the bottom of the list. This creates a hinderance in productivity after loading each file, scrolling back up to the top of the list to load the next file, then scrolling back down again to the bottom if you want to modify its title/caption after loading.

For better usability, I recommend a second "Add Attachments" button below the list of attachments which is rendered with the metabox but with a `hide` class if there are no attachments as the metabox is rendered. Then, add code to simply remove the `hide` class from the second button to the `wpba-media-handler-new.js` file in the `file_frame.on('select')` callback. I'm happy to send a trivial pull request if desired.

**Comment by DHolloran** [comment]
Yeah that sounds like a good idea feel free to send a pr and I will merge it in.  The JS I believe requires Codekit to compile so I can take care of that part if need be.

**Comment by mwarwick** [comment]
Cool, PR is in. Make sure there's nothing else I might be overlooking that binds behaviors to the upper button. Otherwise I will need you to compile `wpba-media-handler-new.min.js` anew to pick up these changes. I wasn't sure in what order you built that file from the source includes. Thanks!

**Comment by DHolloran** [comment]
Sorry, it took me a while to get back, I took care of compiling the JS so it should be good to go. Everything looks good thanks for your help!
